# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: 
    weight: 10

  - name: About us
    url: about-us
    weight: 20

  - name: News 
    url: post
    weight: 30

  - name: Publications 
    url: publication
    weight: 40

  - name: Group members
    weight: 50
    url: /
    identifier: "group-members"
   
  
  - name: Group members
    weight: 9
    url: /people/
    parent: "group-members"

  - name: Faculty
    parent: "group-members"
    url: /faculty/
    weight: 10

  - name: Post Docs
    parent: "group-members"
    url: /post-docs/
    weight: 20
  
  - name: Graduate Students
    parent: "group-members"
    url: /graduate-student/
    wright: 30

  - name: Previous Members
    parent: "group-members"
    url: /past-member/
    wright: 40


  - name: PhD Admissions 
    url: phd_programme_in_advanced_machine_learning
    weight: 60
